### PR TITLE
created ui with basic functionality, no integration with making REST …

### PR DESCRIPTION
**Pull request by ngbalk**
…calls to kie-server yet

---

### CODE REVIEW

**Comment by sabre1041** [comment]
@ngbalk can you ignore the node_modules folder as it's adding 25+mb to therepo

**Comment by sabre1041** [comment]
@ngbalk was able to build and deploy the application in OpenShift. 
- Can you change the default listening port to 8080 as that is the default port used by the nodejs source to image builder?
- When running the application, only the Red Hat logo and the words "The Cool Store" appears. Routing issue that is preventing CSS/JS resources from loading?

**Comment by ngbalk** [comment]
Can now make a call to the kie-server.  Also removed bower as the package manager, only using npm now, much better.  We had to change a small thing in the rules in order for the integration to work, so im going to make a pull request on the rules as well.

**Comment by jgoldsmith613** [comment]
Tried running the app in OSE and receive errors attempting to build


[coolstore.txt](https://github.com/sabre1041/ose-bdd-demo/files/355358/coolstore.txt)

**Comment by sabre1041** [comment]
Tried running the application and an error occurred. The following is a log from the build (OSE nodejs 0.10 image)

[coolstore.log](https://github.com/sabre1041/ose-bdd-demo/files/355359/coolstore.txt)

**Comment by sabre1041** [comment]
Awesome work @ngbalk

**Pull request merged**
